name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run CGLayoutKit's Tests
      run: xcodebuild -project CGLayoutKitExample.xcodeproj -scheme CGLayoutKitExample -destination 'platform=iOS Simulator,name=iPhone 15' test
